# Generated by Django 5.2.1 on 2025-05-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo', models.IntegerField(db_column='codProducto', primary_key=True, serialize=False)),
                ('precioUnitario', models.DecimalField(blank=True, db_column='precioUnitario', decimal_places=0, max_digits=10, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('fechaElaboracion', models.DateField(blank=True, db_column='fechaElaboracion', null=True)),
                ('fechaVencimiento', models.DateField(blank=True, db_column='fechaVencimiento', null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': True,
            },
        ),
    ]
