# Generated by Django 5.2.3 on 2025-06-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_productos_deleted_at_productos_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
