# Generated by Django 5.2.3 on 2025-06-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_delete_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='productos',
            name='preciounitario',
            field=models.DecimalField(blank=True, db_column='precioUnitario', decimal_places=2, max_digits=10, null=True),
        ),
    ]
